### ISSUE TITLE
Espeak我一执行就调出了那个界面

### ISSUE THREAD

**Issue by 15201396130** [Harium/espeak-java#2]
方便加下您微信吗我的微信是zj726181747

**Comment by yuripourre** [comment]
A friend of mine helped me to translate this issue.
Seems that an UI is appearing after calling espeak, right?

Espeak is a command-line application, it doesn't have an interface.

Can you describe what Operating System and espeak version are you using? Do you have espeak-gui (or other gui for espeak) installed?

Translated to Chinese using Google Translate:
我的一个朋友帮我翻译了这个问题。
 似乎在调用espeak后出现了UI，对吗？

 Espeak是一个命令行应用程序，它没有界面。

 您能描述一下您使用的操作系统和espeak版本吗？ 您是否安装了espeak-gui（或espeak的其他gui）？

**Comment by 15201396130** [comment]
我现在是在windows上 后续会部署到linux上 我主要是想 这个系统的效果我测试了下 不知道能不能达到espeak的UI界面的中文转语音的那个流畅的效果 ，目前我下载了这个项目但是转不了中文而且效果太机械了

**Comment by yuripourre** [comment]
Got it. I think I cannot help you since it is related to espeak and not the library itself.
I am closing the issue.

Translated using Google:
得到它了。我想我不能为您提供帮助，因为它与espeak有关，与库本身无关。
我正在解决问题。
