### ISSUE TITLE
怎么调整成中文的

### ISSUE THREAD

**Issue by 15201396130** [Harium/espeak-java#3]
方便加下您微信吗我的微信是zj726181747

**Comment by yuripourre** [comment]
Translating with Google Translate:
`How to adjust to Chinese?`

I never tried to install new languages to espeak. Could you try this?
http://espeak.sourceforge.net/data/

Translated using Google Translate:
我从没尝试过安装新的语言来讲话。 你可以试试这个吗 ?
http://espeak.sourceforge.net/data/

**Comment by 15201396130** [comment]
我测试了 调整不成中文

**Comment by yuripourre** [comment]
I added an example to README using Chinese. I also changed the code to print espeak errors, please upgrade the library to version 1.0.3 so we can investigate further.

Could you please try to use `zh` as the voice name?

Translated by Google:
我在使用中文的自述文件中添加了一个示例。我还更改了代码以打印espeak错误，请将该库升级到1.0.3版，以便我们进行进一步调查。

您能否尝试使用“ zh”作为语音名称？

```
Voice chineseVoice = new Voice();
chineseVoice.setName("zh");
chineseVoice.setAmplitude(100);
chineseVoice.setPitch(30);
chineseVoice.setSpeed(100);
chineseVoice.setVariant("f2");

Espeak woman = new Espeak(chineseVoice);
woman.speak("Nǐ hǎo, shìjiè!");
```

**Comment by yuripourre** [comment]
@15201396130
Since I didn't hear from you and it is working on my machine, I am closing the issue
